name: Azure Auto Shutdown

on:
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * *'   # 8 PM IST

jobs:
  shutdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Verify Login
        run: az account show

      - name: Run Shutdown Script
        run: bash scripts/shutdown.sh
